name: Wiresec Tools Pipeline

on:
  push:
    branches:
      - master

jobs:
  installing-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: wiresec_modules
          key: ${{ runner.os }}-${{ hashFiles('**/apt.lock')}}

      - name: Install dependencies
        run: sudo apt-get install git
